### ISSUE TITLE
Reconstruct the header, and style its media queries

### ISSUE THREAD

**Issue by vragosta** [vragosta/dracobit.io#75]

**Comment by frankieb137** [comment]
mostly finished, feedback and suggestions are welcome :)

**Comment by vragosta** [comment]
Looks great man!

**Suggestions:**
![screen shot 2016-03-22 at 9 39 24 am](https://cloud.githubusercontent.com/assets/10521070/13953373/119dc54c-f012-11e5-836c-7017507add47.png)
Make the input fields width 100%, and increase the height to match the rows for the list items above ( Home, Tutorials, WP-Admin ).  Also make the login button width 100% also, and give it a bootstrap class.

![screen shot 2016-03-22 at 9 39 47 am](https://cloud.githubusercontent.com/assets/10521070/13953410/47cc1326-f012-11e5-8a1d-00769d25f308.png)
This is fine for now, just make the username come before the logout button.

**Comment by frankieb137** [comment]
Increasing the input field height to match the rows for the list items above seemed a bit much so I left it the same for now. 
Login button has a bootstrap class but logout does not (logout button logic made it hard for me to change to bootstrap). 
Otherwise the header is ready to be improved with FlexBox. (By the way, unless something in style.css is blocking you from using FlexBox for a particular item, if you run into anything unnecessary in style.css just leave it don't worry about cleaning up. I want to clean up my own mess lol)

**Comment by vragosta** [comment]
Looked into it, going to reconstruct the template tomorrow at some point if possible, and re style it -- stay tuned.
